name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: "✨ enhancement"
projects: ["verde/1"]
assignees: quantix-dev

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make Verde better with your suggestions.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area does this impact?
      options:
        - Verde CLI
        - Roblox Studio Plugin
        - Verde VSC Extension
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Describe the reason for change
      description: |
        A clear and concise description of why a change needs to be made.
        E.x. Currently unable to use sourcemap.json
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](./.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
