name: Deploy Docs
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["docs/**/*.*", ".github/workflows/deploy-docs.yml"]

defaults:
  run:
    working-directory: ./docs

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # We need all history for doc edit dates
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: './docs/pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm run docs:build

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
