name: Build CLI Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Artifact - ${{ matrix.os }}
    runs-on: ${{ matrix.machine }}
    strategy:
      matrix:
        include:
          - os: windows
            machine: windows-latest
            artifact: verde.exe

          - os: linux
            machine: ubuntu-latest
            artifact: verde
          
          - os: macos
            machine: macos-latest
            artifact: verde
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
      
      - name: Build binary
        run: cargo build --release --locked

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: verde-${{matrix.os}}
          path: target/release/${{ matrix.artifact }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      # We need all history for changelog
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}" 
          output-file: "false"
          skip-commit: "true"
          skip-git-pull: "true"
          version-file: "./Cargo.toml,docs/package.json"

      - uses: actions/download-artifact@v3
        id: download

      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.download.outputs.download-path }}
          file_glob: true
          tag: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.clean_changelog }}